server:
  port: 8003
  
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/banca_app
      
config:
  base.endpoint: http://localhost:8082/api/v1/customers
  
eureka:
  client:
    serviceUrl.defaultZone: http://localhost:8090/eureka      
