server:
  port: 8090
 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  server:
    peer-node-read-timeout-ms: 30000
    

spring:
 cloud:
  gateway:
    routes:
      - id: service-customer
        uri: lb://service-customer
        predicates:
          - Path=/api/v1/customers/**
        filters:
          - StripPrefix=3
      - id: service-cuenta-bancaria
        uri: lb://service-cuenta-bancaria
        predicates:
          - path=/api/v1/cuentaBancaria/**
        filters:
          - StripPrefix=3
      - id: service-credito
        uri: lb://service-credito
        predicates:
          - path=/api/v1/credito/**
        filters:
          - StripPrefix=3
   
