server:
  port: 8005
  
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/banca_app
      
config:
  base.endpoint: http://localhost:8082
  
eureka:
  client:
    serviceUrl.defaultZone: http://localhost:8761/eureka      
